DELETE FROM abbreviation;
DELETE FROM declaration;
DELETE FROM person;
DELETE FROM publication;
DELETE FROM quotation;
DELETE FROM authorship;
DELETE FROM signatory;
DELETE FROM publication_type;
DELETE FROM user;